export default {
    "GET_ALL_STATES_SUCCSESFUL":"GET_ALL_STATES_SUCCSESFUL",
    "LOGIN_USER_SUCCSESFUL":"LOGIN_USER_SUCCSESFUL",
    "LOGIN_USER_ERROR":"LOGIN_USER_ERROR",
    "LOGOUT_USER":"LOGOUT_USER"
}